version: "3.8"
services:
  postgres:
    image: postgres:11.6
    ports:
      - "64000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playground
